### PR TITLE
fix: getting clientWidth on null object

### PR DESCRIPTION
**Pull request by edgesoft**

### CODE REVIEW

**Comment by edgesoft** [comment]
@bokuweb Sorry about the fail. Maybe you could fix this by your self?

**Comment by bokuweb** [comment]
@edgesoft thx, ok.

**Comment by edgesoft** [comment]
@bokuweb Would be great to see the fix. When resizing a get a lot off error messages. The same goes for removing callback in setState. Also produces errors.

**Comment by edgesoft** [comment]
@bokuweb You still have the callback in setState. This will produce error.

**Comment by bokuweb** [comment]
@edgesoft An error does not reproduce my env. `callbacks` is needed to open modal when  `isOpen` default state is `true`.Please tell us about your environment and error log.

**Comment by edgesoft** [comment]
@bokuweb 

``` js
invariant.js?4599:38 Uncaught Invariant Violation: setState(...): 
Expected the last optional `callback` argument to be a function. 
Instead received: Event (keys: isTrusted).
```

When I remove callback from setState the error goes away. The error appears when resizing.

``` js
this.setState({
    height: height,
    width: width,
    top: isOpen ? height * svgMarginRatio : height * (0.5 + svgMarginRatio),
    bottom: isOpen ? height * (1 + svgMarginRatio) : height * (0.5 + svgMarginRatio),
    right: isOpen ? width * (1 + svgMarginRatio) : width * (0.5 + svgMarginRatio),
    left: isOpen ? width * svgMarginRatio : width * (0.5 + svgMarginRatio)
 }, callback);
```

**Comment by edgesoft** [comment]
SetDefaultState can still contain callback.

**Comment by bokuweb** [comment]
@edgesoft  `componentDidMount` need `this.resize` and `callbacks`.

**Pull request merged**
